# Lista 8: Métodos Iterativos para Sistema Lineares e Redução de Dados

### Exercício 3

### (a)

<center>
    <figure>
    <img src="Q1a.jpeg" width=500 align=center>
    </figure>
</center>

### (b)

Uma matriz é diagonal dominante se os modulos dos valores na diagonal sao maiores do que a soma dos modulos dos outros elementos nas respectivas linhas.

Nessa matriz sempre temos o valor 4 na diagonal. Em todas as linhas, temos sempre o valor 0 e duas vezes o valor -1.

Logo, |0| + |-1| + |-1| = 0 + 1 + 1 = 2 < 4.

Logo, a matriz é diagonal dominante.

### (c)

In [7]:
using LinearAlgebra

In [32]:
function gauss_seidel_Q3(A,b; max_iter=1000, ϵ = 1e-3)
    n, m = size(A)
    
    #Calculando o triangular superior e salvando em M
    M = UpperTriangular(A) 
    K = M - A     
    
    #Quebrando a matriz A em M -K, sendo M, a sua triangular superior
    # pois essa é mais barata de se calcular
    R = inv(M) * K
    c = inv(M) * b
    
    #chute inicial
    x = zeros(n,1)
    x_anterior = x
    x = R * x + c

    # condicoes de parada
    iter = 1
    resolvido = (abs(norm(x - x_anterior)) ≤ ϵ)
    cansado = (iter ≥ max_iter)
    
    while !(resolvido || cansado) 
        x_anterior = x
        x=R*x+c 
        iter +=1
        resolvido = (abs(norm(x-x_anterior)) ≤ ϵ)
        cansado = (iter ≥ max_iter)
    end
    print("A tolerância final ficou em $(abs(norm(x-x_anterior)))\n")
    print("O resultado final ficou em $x\n")
    return x
end

gauss_seidel_Q3 (generic function with 1 method)

In [31]:
function gauss_jacobi_Q3(A,b; max_iter=1000, ϵ = 1e-3)
    n, m = size(A)
    
    #Calculando o triangular superior e salvando em M
    M = Diagonal(A) 
    K = M - A     
    
    #Quebrando a matriz A em M -K, sendo M, a sua triangular superior
    # pois essa é mais barata de se calcular
    R = inv(M) * K
    c = inv(M) * b
    
    #chute inicial
    x = zeros(n,1)
    x_anterior = x
    x = R * x + c
    
    # condicoes de parada
    iter = 1
    resolvido = (abs(norm(x - x_anterior)) ≤ ϵ)
    cansado = (iter ≥ max_iter)
    
    while !(resolvido || cansado) 
        x_anterior = x
        x=R*x+c 
        iter +=1
        resolvido = (abs(norm(x-x_anterior)) ≤ ϵ)
        cansado = (iter ≥ max_iter)
    end
    print("A tolerância final ficou em $(abs(norm(x-x_anterior)))\n")
    print("O resultado final ficou em $x\n")
    return x
end

gauss_jacobi_Q3 (generic function with 1 method)

In [28]:
A = [ 4 -1 -1  0;
     -1  4  0 -1;
     -1  0  4 -1;
      0 -1 -1  4]

4×4 Matrix{Int64}:
  4  -1  -1   0
 -1   4   0  -1
 -1   0   4  -1
  0  -1  -1   4

In [29]:
b = [20, 50, 15, 45]

4-element Vector{Int64}:
 20
 50
 15
 45

In [33]:
gauss_seidel_Q3(A,b)

A tolerância final ficou em 0.0006079673767089844
O resultado final ficou em [13.124959468841553; 20.624918937683105; 11.874918937683105; 19.37483787536621]


4×1 Matrix{Float64}:
 13.124959468841553
 20.624918937683105
 11.874918937683105
 19.37483787536621

In [34]:
gauss_jacobi_Q3(A,b)

A tolerância final ficou em 0.0009918212890625
O resultado final ficou em [13.124504089355469; 20.62450408935547; 11.874504089355469; 19.37450408935547]


4×1 Matrix{Float64}:
 13.124504089355469
 20.62450408935547
 11.874504089355469
 19.37450408935547

### (d)

In [ ]:
# codigo julia

### (e)

In [ ]:
# codigo julia

### Exercício 4

### (a)

In [42]:
# Construir matriz A
A = zeros(8,8)
for i = 1:8
    A[i,i] = 1.0
end

A[4,1] = -1.0
A[5,3] = -1.0
A[6,4] = -1.0
A[6,2] = -1.0
A[7,5] = -1.0
A[8,6] = -1.0
A[8,7] = -1.0

A

8×8 Matrix{Float64}:
  1.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   1.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   0.0   1.0   0.0   0.0   0.0   0.0  0.0
 -1.0   0.0   0.0   1.0   0.0   0.0   0.0  0.0
  0.0   0.0  -1.0   0.0   1.0   0.0   0.0  0.0
  0.0  -1.0   0.0  -1.0   0.0   1.0   0.0  0.0
  0.0   0.0   0.0   0.0  -1.0   0.0   1.0  0.0
  0.0   0.0   0.0   0.0   0.0  -1.0  -1.0  1.0

In [43]:
# Cada elemento de b é a soma das demandas com valores explicitos
# associados a uma junta A,B,C...
b = [7000, 3500, 9000, 30000, 3000, 0, 3000, 500]

8-element Vector{Int64}:
  7000
  3500
  9000
 30000
  3000
     0
  3000
   500

In [46]:
# O método converge, mesmo sem respeitar o critério das linhas
gauss_seidel_Q3(A,b)

A tolerância final ficou em 0.0
O resultado final ficou em [7000.0; 3500.0; 9000.0; 37000.0; 12000.0; 40500.0; 15000.0; 56000.0]


8×1 Matrix{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

In [47]:
# O método converge, mesmo sem respeitar o critério das linhas
gauss_jacobi_Q3(A,b)

A tolerância final ficou em 0.0
O resultado final ficou em [7000.0; 3500.0; 9000.0; 37000.0; 12000.0; 40500.0; 15000.0; 56000.0]


8×1 Matrix{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

### (b)