# Lista 8: Métodos Iterativos para Sistema Lineares e Redução de Dados

### Exercício 3

### (a)

<center>
    <figure>
    <img src="Q1a.jpeg" width=500 align=center>
    </figure>
</center>

### (b)

Uma matriz é diagonal dominante se os modulos dos valores na diagonal sao maiores do que a soma dos modulos dos outros elementos nas respectivas linhas.

Nessa matriz sempre temos o valor 4 na diagonal. Em todas as linhas, temos sempre o valor 0 e duas vezes o valor -1.

Logo, |0| + |-1| + |-1| = 0 + 1 + 1 = 2 < 4.

Logo, a matriz é diagonal dominante.

### (c)

In [25]:
using LinearAlgebra

In [63]:
function gauss_seidel_Q3(A,b; max_iter=1000, ϵ = 1e-3, output=true, show_time=false)
    t0 = time()
    n, m = size(A)
    
    #Calculando o triangular superior e salvando em M
    M = UpperTriangular(A) 
    K = M - A     
    
    #Quebrando a matriz A em M -K, sendo M, a sua triangular superior
    # pois essa é mais barata de se calcular
    R = inv(M) * K
    c = inv(M) * b
    
    #chute inicial
    x = zeros(n,1)
    x_anterior = x
    x = R * x + c

    # condicoes de parada
    iter = 1
    resolvido = (abs(norm(x - x_anterior)) ≤ ϵ)
    cansado = (iter ≥ max_iter)
    
    while !(resolvido || cansado) 
        x_anterior = x
        x=R*x+c 
        iter +=1
        resolvido = (abs(norm(x-x_anterior)) ≤ ϵ)
        cansado = (iter ≥ max_iter)
    end
    
    # Tempo do algoritmo
    Δt = time() - t0
    if show_time
        println("Tempo total: $Δt")
    end
    
    # Informacao sobre erro e resultado
    if output
        print("A tolerância final ficou em $(abs(norm(x-x_anterior)))\n")
        print("O resultado final ficou em $x\n")
    end
    
    return x
end

gauss_seidel_Q3 (generic function with 1 method)

In [64]:
function gauss_jacobi_Q3(A,b; max_iter=1000, ϵ = 1e-3, output=true, show_time=false)
    t0 = time()
    n, m = size(A)
    
    #Calculando o triangular superior e salvando em M
    M = Diagonal(A) 
    K = M - A     
    
    #Quebrando a matriz A em M -K, sendo M, a sua triangular superior
    # pois essa é mais barata de se calcular
    R = inv(M) * K
    c = inv(M) * b
    
    #chute inicial
    x = zeros(n,1)
    x_anterior = x
    x = R * x + c
    
    # condicoes de parada
    iter = 1
    resolvido = (abs(norm(x - x_anterior)) ≤ ϵ)
    cansado = (iter ≥ max_iter)
    
    while !(resolvido || cansado) 
        x_anterior = x
        x=R*x+c 
        iter +=1
        resolvido = (abs(norm(x-x_anterior)) ≤ ϵ)
        cansado = (iter ≥ max_iter)
    end
    
    # Tempo do algoritmo
    Δt = time() - t0
    if show_time
        println("Tempo total: $Δt")
    end
    
    if output
        print("A tolerância final ficou em $(abs(norm(x-x_anterior)))\n")
        print("O resultado final ficou em $x\n")
    end
    
    return x
end

gauss_jacobi_Q3 (generic function with 1 method)

In [55]:
A = [ 4 -1 -1  0;
     -1  4  0 -1;
     -1  0  4 -1;
      0 -1 -1  4]

4×4 Matrix{Int64}:
  4  -1  -1   0
 -1   4   0  -1
 -1   0   4  -1
  0  -1  -1   4

In [56]:
b = [20, 50, 15, 45]

4-element Vector{Int64}:
 20
 50
 15
 45

In [57]:
gauss_seidel_Q3(A,b)

A tolerância final ficou em 0.0006079673767089844
O resultado final ficou em [13.124959468841553; 20.624918937683105; 11.874918937683105; 19.37483787536621]


4×1 Matrix{Float64}:
 13.124959468841553
 20.624918937683105
 11.874918937683105
 19.37483787536621

In [34]:
gauss_jacobi_Q3(A,b)

A tolerância final ficou em 0.0009918212890625
O resultado final ficou em [13.124504089355469; 20.62450408935547; 11.874504089355469; 19.37450408935547]


4×1 Matrix{Float64}:
 13.124504089355469
 20.62450408935547
 11.874504089355469
 19.37450408935547

### (d)

In [40]:
# Construindo a matriz A
function create_A(n_lago)
    """ 
        ENTRADA: numero de linhas na matriz do lago (matriz da figura)
        SAIDA: Matriz A que vai representar o calculo das temperaturas
        OBS: o numero de linhas da matriz é sempre o numero de linhas no grafico do lago elevado ao quadrado
            (mantendo o formato quadrado)
    """
    n = n_lago^2
    A = zeros(n,n)

    # Preencher diagonal com 4's
    for i = 1:n
        A[i,i] = 4.0
    end

    # CANTOS DO LAGO

    # Canto superior esquerdo
    A[1,2] = -1.0  # vizinho direita
    A[1,1+n_lago] = -1.0  # vizinho abaixo

    # Canto superior direito
    A[n_lago,n_lago-1] = -1.0  # vizinho esquerda
    A[n_lago,n_lago+n_lago] = -1.0  # vizinho abaixo

    # Canto inferior esquerdo
    i = n - n_lago + 1  
    A[i,i - n_lago] = -1.0  # vizinho acima
    A[i,i+1] = -1.0  # vizinho direita

    # Canto inferior direito
    A[n,n - n_lago] = -1.0  # vizinho acima
    A[n,n-1] = -1.0  # vizinho esquerda

    # BORDAS DO LAGO

    # Borda superior
    for i = 2:n_lago-1
        A[i,i-1] = -1.0  # vizinho esquerda
        A[i,i+1] = -1.0  # vizinho direita
        A[i,i+n_lago] = -1.0  # vizinho abaixo
    end

    # Borda inferior
    x = n - n_lago + 1  # canto inferior esquerdo
    for i = x+1:n-1
        A[i,i-1] = -1.0  # vizinho esquerda
        A[i,i+1] = -1.0  # vizinho direita
        A[i,i-n_lago] = -1.0  # vizinho acima
    end

    # Borda esquerda
    x = n - n_lago + 1  # canto inferior esquerdo
    for i = n_lago+1:n_lago:x-n_lago
        A[i,i-n_lago] = -1.0  # vizinho acima
        A[i,i+1] = -1.0  # vizinho direita
        A[i,i+n_lago] = -1.0  # vizinho abaixo
    end

    # Borda direita
    for i = 2*n_lago:n_lago:n-n_lago
        A[i,i-n_lago] = -1.0  # vizinho acima
        A[i,i-1] = -1.0  # vizinho esquerda
        A[i,i+n_lago] = -1.0  # vizinho abaixo
    end

    # Pontos internos
    x = n - 2*n_lago + 2  # canto inferior esquerdo "interno"
    for i = n_lago+2:n_lago:x  # linhas do quadrado interno
        for j = 0:(n_lago - 3)  # colunas do quadrado interno
            A[i+j,i+j-1] = -1.0  # vizinho esquerda
            A[i+j,i+j+1] = -1.0  # vizinho direita
            A[i+j,i+j-n_lago] = -1.0  # vizinho acima
            A[i+j,i+j+n_lago] = -1.0  # vizinho abaixo
        end
    end

    return A
end

# Usando a letra c como exemplo
A = create_A(2)

4×4 Matrix{Float64}:
  4.0  -1.0  -1.0   0.0
 -1.0   4.0   0.0  -1.0
 -1.0   0.0   4.0  -1.0
  0.0  -1.0  -1.0   4.0

In [46]:
# Construindo vetor b
function create_b(n_lago, T_LEFT, T_TOP, T_RIGHT, T_BOTTOM)
    n = n_lago^2
    b = zeros(n)
    #T_LEFT = 5.0 #25.0
    #T_RIGHT = 35.0 #20.0
    #T_TOP = 15.0 #20.0
    #T_BOTTOM = 10.0 #30.0

    # CANTOS DO LAGO

    # Canto superior esquerdo
    b[1] = T_LEFT + T_TOP

    # Canto superior direito
    b[n_lago] = T_RIGHT + T_TOP

    # Canto inferior esquerdo
    i = n - n_lago + 1  
    b[i] = T_LEFT + T_BOTTOM

    # Canto inferior direito
    b[n] = T_RIGHT + T_BOTTOM

    # BORDAS DO LAGO

    # Borda superior
    for i = 2:n_lago-1
        b[i] = T_TOP
    end

    # Borda inferior
    x = n - n_lago + 1  # canto inferior esquerdo
    for i = x+1:n-1
        b[i] = T_BOTTOM
    end

    # Borda esquerda
    x = n - n_lago + 1  # canto inferior esquerdo
    for i = n_lago+1:n_lago:x-n_lago
        b[i] = T_LEFT
    end

    # Borda direita
    for i = 2*n_lago:n_lago:n-n_lago
        b[i] = T_RIGHT
    end

    # Para os pontos internos vamos manter os zeros

    return b
end

# Usando a letra c como exemplo
b = create_b(2, 5.0, 15.0, 35.0, 10.0)

4-element Vector{Float64}:
 20.0
 50.0
 15.0
 45.0

In [58]:
# Resolvendo o exercicio em si
A = create_A(5)

25×25 Matrix{Float64}:
  4.0  -1.0   0.0   0.0   0.0  -1.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   4.0  -1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   4.0  -1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   4.0  -1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   4.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   0.0   0.0   0.0   0.0   4.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   0.0   0.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  

In [59]:
b = create_b(5, 25.0, 20.0, 20.0, 30.0)

25-element Vector{Float64}:
 45.0
 20.0
 20.0
 20.0
 40.0
 25.0
  0.0
  0.0
  0.0
 20.0
 25.0
  0.0
  0.0
  0.0
 20.0
 25.0
  0.0
  0.0
  0.0
 20.0
 55.0
 30.0
 30.0
 30.0
 50.0

In [77]:
x = gauss_seidel_Q3(A,b, output=false)
reshape(x, (5,5))

5×5 Matrix{Float64}:
 22.6565  23.8638  24.693   25.6011  27.0301
 21.7621  23.1056  24.3072  25.6813  27.5195
 21.2862  22.4896  23.7493  25.2975  27.3668
 20.8933  21.8176  22.903   24.3932  26.6507
 20.4695  20.9848  21.6524  22.7221  24.8431

In [78]:
x = gauss_jacobi_Q3(A,b, output=false)
reshape(x, (5,5))

5×5 Matrix{Float64}:
 22.656   23.8631  24.6922  25.6005  27.0298
 21.7614  23.1045  24.306   25.6803  27.519
 21.2855  22.4884  23.7479  25.2965  27.3663
 20.8927  21.8166  22.902   24.3924  26.6503
 20.4692  20.9843  21.6518  22.7217  24.8429

### (e)

In [87]:
n_lago = 105
A = create_A(n_lago)
b = create_b(n_lago, 25.0, 20.0, 20.0, 30.0)
x = gauss_seidel_Q3(A,b,output=false,show_time=true)
reshape(x, (n_lago,n_lago))

Tempo total: 128.47898983955383


105×105 Matrix{Float64}:
 22.4863  23.4608  23.9119  24.1527  …  25.7236  25.9952  26.4772  27.4827
 21.4843  22.4451  23.0341  23.403      26.3496  26.7801  27.4309  28.4537
 21.0058  21.8013  22.3766  22.7821     26.8468  27.3448  28.0128  28.9012
 20.7376  21.3777  21.8889  22.2809     27.2248  27.7398  28.3746  29.1384
 20.5672  21.083   21.5209  21.8767     27.506   28.0156  28.6077  29.2781
 20.4481  20.8663  21.2352  21.5473  …  27.713   28.2093  28.763   29.3664
 20.359   20.6993  21.0068  21.2742     27.8644  28.3463  28.8691  29.425
 20.2889  20.5652  20.8189  21.0437     27.974   28.4434  28.9426  29.4648
 20.2314  20.454   20.6605  20.8456     28.0521  28.5117  28.9936  29.4922
 20.1829  20.3594  20.524   20.6725     28.1063  28.5589  29.0286  29.5109
 20.141   20.2771  20.4042  20.5191  …  28.1419  28.5902  29.0519  29.5233
 20.104   20.2042  20.2975  20.3813     28.1632  28.6094  29.0664  29.5311
 20.0708  20.1388  20.2013  20.2562     28.1732  28.6193  29.0742  29.5354
 

### Exercício 4

### (a)

In [42]:
# Construir matriz A
A = zeros(8,8)
for i = 1:8
    A[i,i] = 1.0
end

A[4,1] = -1.0
A[5,3] = -1.0
A[6,4] = -1.0
A[6,2] = -1.0
A[7,5] = -1.0
A[8,6] = -1.0
A[8,7] = -1.0

A

8×8 Matrix{Float64}:
  1.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   1.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   0.0   1.0   0.0   0.0   0.0   0.0  0.0
 -1.0   0.0   0.0   1.0   0.0   0.0   0.0  0.0
  0.0   0.0  -1.0   0.0   1.0   0.0   0.0  0.0
  0.0  -1.0   0.0  -1.0   0.0   1.0   0.0  0.0
  0.0   0.0   0.0   0.0  -1.0   0.0   1.0  0.0
  0.0   0.0   0.0   0.0   0.0  -1.0  -1.0  1.0

In [43]:
# Cada elemento de b é a soma das demandas com valores explicitos
# associados a uma junta A,B,C...
b = [7000, 3500, 9000, 30000, 3000, 0, 3000, 500]

8-element Vector{Int64}:
  7000
  3500
  9000
 30000
  3000
     0
  3000
   500

In [46]:
# O método converge, mesmo sem respeitar o critério das linhas
gauss_seidel_Q3(A,b)

A tolerância final ficou em 0.0
O resultado final ficou em [7000.0; 3500.0; 9000.0; 37000.0; 12000.0; 40500.0; 15000.0; 56000.0]


8×1 Matrix{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

In [47]:
# O método converge, mesmo sem respeitar o critério das linhas
gauss_jacobi_Q3(A,b)

A tolerância final ficou em 0.0
O resultado final ficou em [7000.0; 3500.0; 9000.0; 37000.0; 12000.0; 40500.0; 15000.0; 56000.0]


8×1 Matrix{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

### (b)